{
 "title": "Servers Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "duration_milliseconds_bucket" } }
  ]
 },
 "panels": [
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(duration_milliseconds_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "${service} Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"${service}\"\n| stats count() by severityText",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "${service} Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where serviceName=\"${service}\"",
     "timeField": "time"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "go threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{job}}" }
   ]
  }
 ]
}