
name: Build and Push Connect Container
on:
  push:
    branches:
      - main
    paths:
      - 'connect/**'
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: ./connect/go.mod
      # use a specific commit of the ko-build/setup-ko action that includes lower casing of docker repo name.
      - uses: ko-build/setup-ko@f6bcbe6bd48f22c3dc2f08049d856cf0fc719d96 #v0.6 + latest commits as of 2024-04-12
      - run: ko build ./cmd/connect --base-import-paths
        working-directory: ./connect