name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Go Build
        working-directory: ./connect
        run: go build 

  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: .NET Build
        working-directory: ./dotnet
        run: dotnet build --configuration Release